### ISSUE TITLE
ES6 default export doesn't work with node 8.x

### ISSUE THREAD

**Issue by gwillz** [pascalduez/postcss-scrollbar#1]
Or something along those lines.

This plugin cannot be loaded when using node 8.x and using a PostCSS config like below:

```js
module.exports = {
  plugins: {
    'postcss-import': {},
    'postcss-scrollbar': {},
    'cssnano': {}
  }
}
```

Here PostCSS will expect plugins listed to be CommonJS type modules and flat-out refuses to import 'postcss-scrollbar'. Alternatively, one could use the `require('postcss-scrollbar').default({})` method as a workaround.

For a fix, I suggest changing the export statement to this:
```js
module.exports = postcss.plugin(...);
module.exports.default = module.exports;
module.exports.__esModule = true;
```

This is somewhat how babel does its transpiled exports. Here we're just doing it manually but also exporting the plugin in a CommonJS compatible way.

There is also a [babel plugin](https://www.npmjs.com/package/babel-plugin-add-module-exports) that does this if you don't want to dirty up your neat ES6 code.

**Comment by pascalduez** [comment]
Hi,

thanks for reporting. Should be fixed as of version `0.2.1`.
