### ISSUE TITLE
issue using REM unit

### ISSUE THREAD

**Issue by sylvainbaronnet** [pascalduez/postcss-scrollbar#9]
Hi, Why using rem unit ? I have custom small font-size on html, and it makes scrollbar almost invisible on chrome.
Plus I think rem for scrollbar only works on chrome, on Safari it's treated without taking root font-size into account.

**Comment by sylvainbaronnet** [comment]
Also it would be nice to allow to specify custom width directly

**Comment by pascalduez** [comment]
Fixed as of `0.4.0`

**Comment by sylvainbaronnet** [comment]
Great, thanks!
